from enum import Enum, auto


class ZaoEventType(Enum):
    UNKNOWN = auto()
    DIARY = auto()
    CODING = auto()
    HAIR_CUT = auto()
    NAIL_CUT = auto()
    BEATEN = auto()
    BEATING = auto()
    ABUSE = auto()
    MENSTRUAL = auto()
    READING = auto()
    WRITING = auto()
    ENJOY = auto()
    NIGHTMARE = auto()
    INSOMNIA = auto()
    CATCHING = auto()
    MONEY = auto()
    BIRTH = auto()
    DEATH = auto()
    WEDDING = auto()
    DIVORCE = auto()
    TODO = auto()
    INSPECT = auto()
    CRITICIZE = auto()


class ZaoRelationship(Enum):
    UNKNOWN = auto()
    FAMILY = auto()
    BLOOD = auto()
    AFFINITY = auto()
    SHAO_WU = auto()
    NAN_PING = auto()
    FU_JIAN = auto()
    LAN_ZHOU = auto()
    UTILITY = auto()
    ANCHOR = auto()
    NEW_EGG = auto()
    MEI_TUAN = auto()
